version:  '3'
services:
  juice-shop:
    build:
      dockerfile: Dockerfile
      context: ./juice-shop
    ports:
        - '3000:3000'

  nginx-reverse-proxy:
    build:
      dockerfile: Dockerfile
      context: ./nginx-reverse-proxy
    ports:
      - '80:80'
